In [1]:
import numpy as np
import joblib

In [2]:
svmin = np.load('svminput.npy')
rfin = np.load('rfinput.npy')
print(svmin)
print(rfin)

[[  0.49201301   0.22319216  -2.37841034  -0.78340191   0.93923843]
 [  0.49201301   0.22319213  -2.37841034  -0.77991259   0.93923843]
 [  0.49201301   0.22319205  -2.37841034  -0.77607435   0.93923843]
 ...
 [  2.20241189 -19.66461372   0.58657449  -0.78584397   0.93923843]
 [  2.14216685 -23.94061661   0.58633918  -0.78584397   0.93923843]
 [ -2.00201964 -32.60622787   0.58610904  -0.78584397   0.93923843]]
[[  0.49201301   0.22319216  -2.37841034  -0.78340191   0.93923843]
 [  0.49201301   0.22319213  -2.37841034  -0.77991259   0.93923843]
 [  0.49201301   0.22319205  -2.37841034  -0.77607435   0.93923843]
 ...
 [  2.20241189 -19.66461372   0.58657449  -0.78584397   0.93923843]
 [  2.14216685 -23.94061661   0.58633918  -0.78584397   0.93923843]
 [ -2.00201964 -32.60622787   0.58610904  -0.78584397   0.93923843]]


In [5]:
svm = joblib.load('svm.pkl')

svmout = svm.predict(svmin)
print(svmout)

F:\Python\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator SVR from version 0.23.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


AttributeError: 'SVR' object has no attribute 'probA_'