In [29]:
import numpy as np

w = np.random.randn(5,1)
print(w)
print('= = = = ')

x = np.random.randn(1,5)
print(x)
print('= = = = ')

D = w.dot(x)
print(D)
print('= = = = ')

dD = np.random.randn(*D.shape)
print(dD)

[[ 0.37483536]
 [-0.4950004 ]
 [ 0.82235805]
 [-1.36801803]
 [ 0.03883433]]
= = = = 
[[-0.99202896  0.71732229  0.64519076 -1.11537264  1.23611161]]
= = = = 
[[-0.37184753  0.26887776  0.24184031 -0.41808111  0.46333834]
 [ 0.49105473 -0.35507482 -0.31936969  0.5521099  -0.61187574]
 [-0.815803    0.58989576  0.53057782 -0.91723567  1.01652633]
 [ 1.3571135  -0.98130983 -0.8826326   1.52584988 -1.69102297]
 [-0.03852478  0.02785673  0.02505555 -0.04331474  0.04800356]]
= = = = 
[[ 0.08545029 -0.90962466  0.30121181 -0.68490131  0.86335318]
 [ 0.60497321 -0.98974085  1.23094273 -1.42600226  0.50965974]
 [-1.41112795  0.22334232  0.09912216 -1.5010084  -1.49243366]
 [-0.66970493  0.53454501  1.92544683 -0.19339168  0.1061864 ]
 [ 1.29404049 -1.73681565  1.12803352 -0.01675582  0.37703076]]
