# Tensorflow2.0 小练习

In [2]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [3]:
a = np.array([1,2,3,4])
print(np.max(a))

4


In [4]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########

    tmp = np.exp(x)
    prob_x = tmp / np.reshape(np.sum(tmp, axis=-1),(-1,1))

    return prob_x

test_data = np.random.normal(size=[10, 5])

(softmax(test_data) - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [7]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    # tmp = np.exp(x)
    prob_x = 1 / (1+tf.math.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [51]:
a = np.array([1,-1,0,2,3])
print(a)
d = tf.reduce_mean(a)
print('d ->', d)

c = tf.where((a > 0) | (a < 0))
print(c)

b = tf.gather_nd(a,c)
print('b', b)

[ 1 -1  0  2  3]
d -> tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(
[[0]
 [1]
 [3]
 [4]], shape=(4, 1), dtype=int64)
b tf.Tensor([ 1 -1  2  3], shape=(4,), dtype=int32)


In [47]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    res = -label*tf.math.log(x)
    idx = tf.where((res > 0) | (res < 0))
    loss = tf.gather_nd(res,idx)
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

# ((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
#   - softmax_ce(prob, label))**2 < 0.0001).numpy()

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label,test_data))
  - tf.reduce_mean(softmax_ce(prob, label)))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [53]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    loss = tf.math.reduce_mean(-label*tf.math.log(x)-(1-label)*tf.math.log(1-x))
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[0. 0. 1. 1. 0. 0. 1. 0. 1. 0.]


True

In [41]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    res=-label*tf.math.log(prob)
    idx = tf.where((res >0) | (res <0))
    output = tf.gather_nd(res, idx)
    return output

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

# test_data=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])  
# prob=tf.nn.softmax(logits)
# label=tf.constant([[0.0,0.0,1.0],[0.0,0.0,1.0],[0.0,0.0,1.0]]) 

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label,test_data))
  - tf.reduce_mean(softmax_ce(prob, label)))**2 < 0.0001).numpy()


True