In [51]:
import numpy as np

w = np.random.randn(5,1)
print(w)
print('= = = = ')

x = np.random.randn(1,5)
print(x)
print('= = = = ')

D = w.dot(x)
print(D)
print('= = = = ')

dD = np.random.randn(*D.shape)
print(dD)


a = np.array([[1, 2],[3, 4]])

print(a)
b = np.array([[1, 1], [1,1]])
print(b)
print(b.dot(a))

[[-1.06714902]
 [-1.68480211]
 [-0.09214341]
 [-1.17260435]
 [ 0.01765593]]
= = = = 
[[-0.0405879   1.3094696   0.73447837  0.5932362  -0.20233608]]
= = = = 
[[ 4.33133402e-02 -1.39739921e+00 -7.83797875e-01 -6.33071428e-01
   2.15922753e-01]
 [ 6.83825832e-02 -2.20619715e+00 -1.23745071e+00 -9.99485595e-01
   3.40896258e-01]
 [ 3.73990773e-03 -1.20658995e-01 -6.76773419e-02 -5.46628064e-02
   1.86439367e-02]
 [ 4.75935505e-02 -1.53548975e+00 -8.61252530e-01 -6.95631343e-01
   2.37260170e-01]
 [-7.16617303e-04  2.31199083e-02  1.29679013e-02  1.04741389e-02
  -3.57243242e-03]]
= = = = 
[[ 0.07954632  1.56728689 -0.39875884  0.86484194  0.66698549]
 [-1.26602208  2.11009241  0.26657476  1.32643509  1.28742829]
 [-0.11506769 -1.43335143  2.034541   -1.64027939  1.96910953]
 [ 2.19876889  0.16302374 -1.00928201  1.2553298   0.11360611]
 [-0.50742175 -0.6097796   0.56021626 -1.668111    1.38937145]]
[[1 2]
 [3 4]]
[[1 1]
 [1 1]]
[[4 6]
 [4 6]]
