In [64]:
from embedding import LoadWord2VecEmbedding

In [65]:
# f = 'D:\DataModel\word2vec\w2v_zh\sgns.weibo.word'
# w2v = LoadWord2VecEmbedding(f)


In [66]:
embed_path = 'D:\DataModel\WordEmbedding_zh\sgns.weibo.bigram'
embed = LoadWord2VecEmbedding(embed_path)


In [67]:
vec = embed.get_vectors()
print(vec)

[[ 0.777821 -0.93826  -0.615527 ... -0.045383  0.046151  1.326254]
 [ 0.489674 -0.339039 -0.907787 ... -0.634991  1.451896  0.270008]
 [-0.206359 -0.182874 -1.394484 ... -0.303575  0.590271  0.676646]
 ...
 [ 0.073822  0.083244 -0.089985 ... -0.042876  0.083995  0.146762]
 [ 0.043174  0.108385 -0.077019 ... -0.004407  0.118902  0.028844]
 [ 0.087763 -0.026256 -0.079862 ... -0.024056 -0.005424  0.07694 ]]


In [68]:
w2v = embed.get_model()
w2v.index_to_key

['，',
 '的',
 '。',
 '@',
 '！',
 '了',
 '、',
 '：',
 '是',
 '一',
 '有',
 '】',
 '？',
 '在',
 '我',
 '你',
 '和',
 '个',
 '�',
 '不',
 '人',
 '“',
 '一个',
 '就',
 '都',
 '也',
 '我们',
 '要',
 '#',
 '好',
 '”',
 '啊',
 '这',
 '去',
 ',',
 '；',
 '很',
 '月',
 '还',
 '.',
 '1',
 '微博',
 '》',
 '上',
 '会',
 '说',
 '《',
 '~',
 '年',
 '吧',
 '小',
 '大',
 '天',
 '能',
 '-',
 '吃',
 '来',
 '自己',
 '让',
 '可以',
 '给',
 ':',
 '到',
 '看',
 '就是',
 '最',
 '（',
 '为',
 '中国',
 '多',
 '与',
 '中',
 '北京',
 '这个',
 '[',
 '爱',
 '他',
 ']',
 '做',
 '日',
 '【',
 '把',
 '想',
 '又',
 '没有',
 '2',
 '什么',
 '大家',
 '旅游',
 '被',
 '对',
 '吗',
 '过',
 '不是',
 '将',
 '之',
 '。。。',
 '）',
 '呢',
 '3',
 '等',
 '着',
 '啦',
 '里',
 '酒店',
 '点',
 '太',
 '没',
 '但',
 '用',
 '今天',
 '两',
 '哦',
 '还是',
 '第',
 '……',
 '而',
 '三',
 '――',
 '次',
 '喜欢',
 '分享',
 '从',
 '后',
 '知道',
 '5',
 '种',
 '那',
 '得',
 '4',
 '一起',
 '这样',
 '��',
 '下',
 '您',
 '活动',
 '?',
 '(',
 '们',
 '你们',
 '现在',
 '生活',
 '时候',
 '请',
 '才',
 '时',
 '再',
 '世界',
 '更',
 '她',
 '地',
 '～',
 '开始',
 '第一',
 '10',
 '!',
 '还有',
 '可',
 '这里',
 '几',
 '

In [69]:
embed.idx2word(0)

'，'

In [70]:
mdl = embed.get_model()

In [71]:
import numpy as np


class BuildMyW2VFromLargeW2V:
    def __init__(self, corpus: list, large_embdding_path: str):
        self.corpus = corpus
        self.large_embdding_loader = LoadWord2VecEmbedding(large_embdding_path)
        # self.large_embdding_loader = embed
        self.large_w2v = self.large_embdding_loader.get_model()
        self.vector_size = self.large_w2v.vector_size

        self.token2vector = {}
        for token in self.corpus:
            if token in self.large_embdding_loader.get_vocab():
                self.token2vector[token] = self.large_embdding_loader.word2vec(word=token)[token]
            else:
                self.token2vector[token] = np.zeros(self.vector_size)

    def get_vocab(self) -> dict:
        vocab = {token: i for i, token in enumerate(self.corpus)}
        return vocab

    def get_vectors(self) -> np.ndarray:
        vectors = np.conj(list(self.token2vector.values()))
        return vectors

    def token2vec(self, token=None):
        if token and token in self.token2vector:
            return {token: self.token2vector[token]}
        else:
            return self.token2vector


In [72]:

# def corpus(self):


corpus = ['你', '好', '六']

BMWL = BuildMyW2VFromLargeW2V(corpus, embed_path)
BMWL

In [74]:
BMWL.token2vec()

{'你': array([ 0.386387,  0.255612,  0.174639, -0.137603,  0.005572, -0.334268,
        -0.712347, -0.720909, -0.171396, -0.323724,  0.745168,  0.445946,
         0.217458,  0.835762,  0.5097  ,  0.388918, -0.927338,  0.78951 ,
         1.10496 , -1.005923, -0.436329,  1.344794,  0.723849,  1.10659 ,
         0.470562,  0.204864,  0.569014,  0.857835,  0.421609, -0.549315,
        -0.132153,  0.701314,  0.805109, -0.20013 ,  0.723825, -0.353035,
        -0.63252 , -0.01246 ,  0.46454 , -0.278661, -1.070403, -0.542021,
         0.689054,  0.243103, -1.429973, -0.685935,  0.546376, -0.717446,
         0.05167 ,  0.200119,  0.545371,  0.039136, -0.548174,  1.22597 ,
        -0.042701, -0.316304, -1.052576, -0.060243,  0.072116,  0.755501,
         0.706978, -1.334361,  0.937635,  0.045355,  0.154896, -0.155844,
         0.190729,  0.587605,  0.669013, -0.39035 ,  0.218968, -0.89096 ,
         0.223705, -0.545403, -0.567843, -0.13694 , -0.818778,  0.146563,
        -0.219047,  0.517889,  0.