In [28]:
import torch
import numpy as np

 

## 1. 初始化Tensor
创建Tensor有多种方法，如：

### 1.1 直接从数据创建

可以直接利用数据创建tensor,数据类型会被自动推断出

In [29]:
data = [[1,2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


### 1.2 从numpy创建
Tensor 可以直接从numpy的array创建（反之亦然-参见bridge-to-np-label）

In [30]:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)


[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


### 1.3 从其他tensor创建

新的tensor保留了参数tensor的一些属性（形状，数据类型），除非显式覆盖

In [31]:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6175, 0.3302],
        [0.0626, 0.4073]])


### 1.4 从常数或者随机数创建

shape是关于tensor维度的一个元组，在下面的函数中，它决定了输出tensor的维数。

In [32]:
shape = (3,4)
rand_tensor = torch.rand(shape)#0~1
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.7629, 0.1639, 0.6383, 0.3556],
        [0.1768, 0.1827, 0.3609, 0.6944],
        [0.7451, 0.2434, 0.3485, 0.0440]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


## 2. Tensor的属性
Tensor的属性包括形状，数据类型以及存储的设备

In [33]:
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


## 3. Tensor的操作
Tensor有超过100个操作，包括 transposing, indexing, slicing, mathematical operations, linear algebra, random sampling,更多详细的介绍请点击这里

它们都可以在GPU上运行（速度通常比CPU快），如果你使用的是Colab，通过编辑>笔记本设置来分配一个GPU。

[官方PyTorch-GPU版本安装](https://pytorch.org/get-started/locally/)

In [34]:
flag = torch.cuda.is_available()
print(flag)
if flag:
    tensor = tensor.to('cuda')
print(tensor.device)

True
cuda:0


尝试列表中的一些操作。如果你熟悉NumPy API，你会发现tensor的API很容易使用。

### 3.1 标准的numpy类索引和切片:

In [35]:
tensor = torch.ones(3,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 3.2 合并tensors
可以使用torch.cat来沿着特定维数连接一系列张量。 torch.stack另一个加入op的张量与torch.cat有细微的不同

In [36]:
t1 = torch.cat([tensor,  tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### 3.3 增加tensors

In [37]:
# 矩阵乘法
t2 = tensor.matmul(tensor.T)
t3 = tensor @ tensor.T
print(t2)
print(t3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


## 3.4 原地操作
带有后缀_的操作表示的是原地操作，例如： x.copy_(y), x.t_()将改变 x.

In [38]:
print(tensor,'\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## 4. Tensor转换为Numpy 数组

In [39]:
t = torch.ones(5)
n = t.numpy()
print(t,'\n')
print(n)

tensor([1., 1., 1., 1., 1.]) 

[1. 1. 1. 1. 1.]


tensor的变化反映在NumPy数组中。

In [40]:
t.add_(1)
print(t,'\n')
print(n)

tensor([2., 2., 2., 2., 2.]) 

[2. 2. 2. 2. 2.]


### 4.1 Numpy数组转换为Tensor

In [41]:
n = np.ones(5)
t = torch.from_numpy(n)
print(n,'\n')
print(t)


[1. 1. 1. 1. 1.] 

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [44]:
np.add(n, 1, out=n)
print(n,'\n')
print(t)





[4. 4. 4. 4. 4.] 

tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
